AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 
  Stage:
    Type: String

Mappings: 
  Environment:
    dev:
      stackName: dev-stack
      bucket: product
    uat:
      stackName: uat-stack
      bucket: product

Conditions: 

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [ Environment, !Ref 'Stage', bucket ]

  s3Bucket1:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private | PublicRead | PublicReadWrite | AuthenticatedRead | LogDeliveryWrite | BucketOwnerRead | BucketOwnerFullControl
      BucketName: 
      CorsConfiguration: 
      LifecycleConfiguration: 
      NotificationConfiguration: 
      VersioningConfiguration: 
      WebsiteConfiguration: 
      Tags:
        - Key: key
          Value: value


Outputs: